/* Generated by c_code_generator */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>


int main(void)
{
   int32_t a = 7;
   int32_t b = 11;
   int32_t sum = (a + b);
   printf("a=%d\n", a);
   fflush(stdout);
   printf("b=%d\n", b);
   fflush(stdout);
   printf("sum=%d\n", sum);
   fflush(stdout);
   printf("Press Enter to exit...\n");
   fflush(stdout);
   {
      int cgenWaitChar = 0;
      while (((cgenWaitChar = getchar()) != '\n') && (cgenWaitChar != EOF))
      {
      }
      if (cgenWaitChar != EOF)
      {
         while (((cgenWaitChar = getchar()) != '\n') && (cgenWaitChar != EOF))
         {
         }
      }
   }
   return 0;
}
