/* Generated by c_code_generator */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>


int main(void)
{
   int32_t a = 7;
   int32_t b = 11;
   int32_t sum = (a + b);
   printf("a=%d\n", a);
   printf("b=%d\n", b);
   printf("sum=%d\n", sum);
   return 0;
}
