/* Generated by c_code_generator */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>



int main(void)
{
   srand((unsigned int)time(NULL));
   int32_t totalLen;
   int32_t numDigits;
   int32_t numSpecial;
   int32_t numUpper;
   int32_t numLower;
   int32_t pos = 0;
   char password[256];
   printf("How many characters (total length)? ");
   fflush(stdout);
   if (scanf("%d", &totalLen) != 1)
   {
      totalLen = 0;
   }
   printf("How many numbers? ");
   fflush(stdout);
   if (scanf("%d", &numDigits) != 1)
   {
      numDigits = 0;
   }
   printf("How many special characters? ");
   fflush(stdout);
   if (scanf("%d", &numSpecial) != 1)
   {
      numSpecial = 0;
   }
   printf("How many capitalized letters? ");
   fflush(stdout);
   if (scanf("%d", &numUpper) != 1)
   {
      numUpper = 0;
   }
   numLower = (((totalLen - numDigits) - numSpecial) - numUpper);
   if ((numLower < 0))
   {
      printf("Error: numbers + specials + capitals exceed total length.\n");
      fflush(stdout);
   }
   else
   {
      for (int32_t lowerIndex = 0; lowerIndex < numLower; ++lowerIndex)
      {
         password[pos] = (char)(((int32_t)('a' + (rand() % 26))));
         pos = (pos + 1);
      }
      for (int32_t upperIndex = 0; upperIndex < numUpper; ++upperIndex)
      {
         password[pos] = (char)(((int32_t)('A' + (rand() % 26))));
         pos = (pos + 1);
      }
      for (int32_t digitIndex = 0; digitIndex < numDigits; ++digitIndex)
      {
         password[pos] = (char)(((int32_t)('0' + (rand() % 10))));
         pos = (pos + 1);
      }
      for (int32_t specialIndex = 0; specialIndex < numSpecial; ++specialIndex)
      {
         password[pos] = (char)(((int32_t)("!@#$%&*?"[rand() % 8])));
         pos = (pos + 1);
      }
      password[pos] = (char)(0);
      {
         int32_t cgenShuffleLen = (int32_t)(pos);
         for (int32_t cgenShuffleIndex = cgenShuffleLen - 1; cgenShuffleIndex > 0; --cgenShuffleIndex)
         {
            int32_t cgenShuffleSwap = rand() % (cgenShuffleIndex + 1);
            char cgenShuffleTemp = password[cgenShuffleIndex];
            password[cgenShuffleIndex] = password[cgenShuffleSwap];
            password[cgenShuffleSwap] = cgenShuffleTemp;
         }
      }
      printf("Password: %s\n", password);
      fflush(stdout);
   }
   printf("Press Enter to exit...\n");
   fflush(stdout);
   (void)getchar();
   return 0;
}
