/* Generated by c_code_generator */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>


void print_board(char* board)
{
   printf("\n %c | %c | %c\n", ((int32_t)(board[0])), ((int32_t)(board[1])), ((int32_t)(board[2])));
   fflush(stdout);
   printf("---+---+---\n");
   fflush(stdout);
   printf(" %c | %c | %c\n", ((int32_t)(board[3])), ((int32_t)(board[4])), ((int32_t)(board[5])));
   fflush(stdout);
   printf("---+---+---\n");
   fflush(stdout);
   printf(" %c | %c | %c\n\n", ((int32_t)(board[6])), ((int32_t)(board[7])), ((int32_t)(board[8])));
   fflush(stdout);
   return;
}

int32_t check_winner(char* board)
{
   if ((((int32_t)(board[0])) == ((int32_t)(board[1]))))
   {
      if ((((int32_t)(board[1])) == ((int32_t)(board[2]))))
      {
         if ((((int32_t)(board[0])) != ' '))
         {
            return ((int32_t)(board[0]));
         }
      }
   }
   if ((((int32_t)(board[3])) == ((int32_t)(board[4]))))
   {
      if ((((int32_t)(board[4])) == ((int32_t)(board[5]))))
      {
         if ((((int32_t)(board[3])) != ' '))
         {
            return ((int32_t)(board[3]));
         }
      }
   }
   if ((((int32_t)(board[6])) == ((int32_t)(board[7]))))
   {
      if ((((int32_t)(board[7])) == ((int32_t)(board[8]))))
      {
         if ((((int32_t)(board[6])) != ' '))
         {
            return ((int32_t)(board[6]));
         }
      }
   }
   if ((((int32_t)(board[0])) == ((int32_t)(board[3]))))
   {
      if ((((int32_t)(board[3])) == ((int32_t)(board[6]))))
      {
         if ((((int32_t)(board[0])) != ' '))
         {
            return ((int32_t)(board[0]));
         }
      }
   }
   if ((((int32_t)(board[1])) == ((int32_t)(board[4]))))
   {
      if ((((int32_t)(board[4])) == ((int32_t)(board[7]))))
      {
         if ((((int32_t)(board[1])) != ' '))
         {
            return ((int32_t)(board[1]));
         }
      }
   }
   if ((((int32_t)(board[2])) == ((int32_t)(board[5]))))
   {
      if ((((int32_t)(board[5])) == ((int32_t)(board[8]))))
      {
         if ((((int32_t)(board[2])) != ' '))
         {
            return ((int32_t)(board[2]));
         }
      }
   }
   if ((((int32_t)(board[0])) == ((int32_t)(board[4]))))
   {
      if ((((int32_t)(board[4])) == ((int32_t)(board[8]))))
      {
         if ((((int32_t)(board[0])) != ' '))
         {
            return ((int32_t)(board[0]));
         }
      }
   }
   if ((((int32_t)(board[2])) == ((int32_t)(board[4]))))
   {
      if ((((int32_t)(board[4])) == ((int32_t)(board[6]))))
      {
         if ((((int32_t)(board[2])) != ' '))
         {
            return ((int32_t)(board[2]));
         }
      }
   }
   return 0;
}

int main(void)
{
   srand((unsigned int)time(NULL));
   int32_t playing = 1;
   int32_t row = 0;
   int32_t col = 0;
   int32_t idx = 0;
   int32_t turn = 0;
   int32_t moves = 0;
   int32_t winner = 0;
   int32_t placed = 0;
   int32_t cell = 0;
   int32_t roundActive = 0;
   char again = '\0';
   char board[9];
   printf("Tic Tac Toe — you are X, AI is O (random moves).\n");
   fflush(stdout);
   printf("Enter row and column as 1-3. After a game, press r to restart.\n");
   fflush(stdout);
   while ((playing == 1))
   {
      for (int32_t clearIndex = 0; clearIndex < 9; ++clearIndex)
      {
         board[clearIndex] = (char)(' ');
      }
      moves = 0;
      winner = 0;
      roundActive = 1;
      turn = (rand() % 2);
      if ((turn == 0))
      {
         printf("You start first (X).\n");
         fflush(stdout);
      }
      else
      {
         printf("AI starts first (O).\n");
         fflush(stdout);
      }
      while ((roundActive == 1))
      {
         print_board(board);
         if ((turn == 0))
         {
            printf("Your move (X).\n");
            fflush(stdout);
            placed = 0;
            while ((placed == 0))
            {
               printf("Row (1-3): ");
               fflush(stdout);
               if (scanf("%d", &row) != 1)
               {
                  row = 0;
               }
               printf("Col (1-3): ");
               fflush(stdout);
               if (scanf("%d", &col) != 1)
               {
                  col = 0;
               }
               if ((row == 0))
               {
                  playing = 0;
                  roundActive = 0;
                  winner = -1;
                  placed = 1;
               }
               else
               {
                  idx = (((row - 1) * 3) + (col - 1));
                  if ((row >= 1))
                  {
                     if ((row <= 3))
                     {
                        if ((col >= 1))
                        {
                           if ((col <= 3))
                           {
                              if ((((int32_t)(board[idx])) == ' '))
                              {
                                 board[idx] = (char)('X');
                                 placed = 1;
                              }
                              else
                              {
                                 printf("That cell is taken. Try again.\n");
                                 fflush(stdout);
                              }
                           }
                           else
                           {
                              printf("Invalid row/col. Use 1-3.\n");
                              fflush(stdout);
                           }
                        }
                        else
                        {
                           printf("Invalid row/col. Use 1-3.\n");
                           fflush(stdout);
                        }
                     }
                     else
                     {
                        printf("Invalid row/col. Use 1-3.\n");
                        fflush(stdout);
                     }
                  }
                  else
                  {
                     printf("Invalid row/col. Use 1-3.\n");
                     fflush(stdout);
                  }
               }
            }
         }
         else
         {
            printf("AI move (O)...\n");
            fflush(stdout);
            placed = 0;
            while ((placed == 0))
            {
               cell = (rand() % 9);
               if ((((int32_t)(board[cell])) == ' '))
               {
                  board[cell] = (char)('O');
                  placed = 1;
                  printf("AI played row %d, col %d.\n", ((cell / 3) + 1), ((cell % 3) + 1));
                  fflush(stdout);
               }
            }
         }
         if ((playing == 1))
         {
            moves = (moves + 1);
            winner = check_winner(board);
            if ((winner != 0))
            {
               roundActive = 0;
            }
            else
            {
               if ((moves >= 9))
               {
                  roundActive = 0;
               }
               else
               {
                  turn = (1 - turn);
               }
            }
         }
      }
      print_board(board);
      if ((winner == 'X'))
      {
         printf("You win!\n");
         fflush(stdout);
      }
      else
      {
         if ((winner == 'O'))
         {
            printf("AI wins!\n");
            fflush(stdout);
         }
         else
         {
            if ((winner == 0))
            {
               printf("Draw.\n");
               fflush(stdout);
            }
         }
      }
      if ((winner != -1))
      {
         printf("Press r to restart, or any other key to quit: ");
         fflush(stdout);
         if (scanf(" %c", &again) != 1)
         {
            again = '\0';
         }
         if ((again == 'r'))
         {
         }
         else
         {
            playing = 0;
         }
      }
   }
   printf("Goodbye.\n");
   fflush(stdout);
   return 0;
}
